version: "3.8"

name: rtos

services:
  nodered:
    image: nodered/node-red:latest
    container_name: rtos-nodered
    ports:
      - "1880:1880"
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - nodered_data:/data
    networks:
      - power-monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: rtos-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    networks:
      - power-monitoring
    depends_on:
      - nodered

  grafana:
    image: grafana/grafana:latest
    container_name: rtos-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - power-monitoring
    depends_on:
      - prometheus

  emqx:
    image: emqx:latest
    container_name: rtos-emqx
    environment:
    - "EMQX_NODE__NAME=emqx@node.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    networks:
      power-monitoring:
        aliases:
        - node.emqx.io
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083

  flask_server:
    build: ./src
    container_name: rtos-flask
    ports:
      - 5000:5000
    networks:
      - power-monitoring

volumes:
  nodered_data:
  grafana_data:
  prometheus_data:

networks:
  power-monitoring:
    driver: bridge
